// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtRfPO1ZygycOyCD08PuwVeMu0Tar384',
    appId: '1:652371615013:web:cbdd881850829cd669cecc',
    messagingSenderId: '652371615013',
    projectId: 'chat-app-2b4c2',
    authDomain: 'chat-app-2b4c2.firebaseapp.com',
    storageBucket: 'chat-app-2b4c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzcTtiXHfBYC-wniLLh0JFXF2wqemw_2M',
    appId: '1:652371615013:android:ab783a564d920c6269cecc',
    messagingSenderId: '652371615013',
    projectId: 'chat-app-2b4c2',
    storageBucket: 'chat-app-2b4c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-l6KLkH90TyIS_3FMwhRlgvQ6JqaEpNQ',
    appId: '1:652371615013:ios:d27773b1b9852b8a69cecc',
    messagingSenderId: '652371615013',
    projectId: 'chat-app-2b4c2',
    storageBucket: 'chat-app-2b4c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-l6KLkH90TyIS_3FMwhRlgvQ6JqaEpNQ',
    appId: '1:652371615013:ios:d27773b1b9852b8a69cecc',
    messagingSenderId: '652371615013',
    projectId: 'chat-app-2b4c2',
    storageBucket: 'chat-app-2b4c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwtRfPO1ZygycOyCD08PuwVeMu0Tar384',
    appId: '1:652371615013:web:7c4935b66938870369cecc',
    messagingSenderId: '652371615013',
    projectId: 'chat-app-2b4c2',
    authDomain: 'chat-app-2b4c2.firebaseapp.com',
    storageBucket: 'chat-app-2b4c2.firebasestorage.app',
  );
}
